version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: railsWeb
      MYSQL_USER: thanhhung
      MYSQL_PASSWORD: password
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/railsWeb"
    depends_on:
      - db
    links:
      - db
    ports:
      - "3001:3000"
    environment:
      DB_USER: root
      DB_NAME: railsWeb
      DB_PASSWORD: password
      DB_HOST: db
  